# Generated by Django 4.2.7 on 2023-11-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_teacher', models.CharField(max_length=30)),
                ('name_teacher', models.CharField(max_length=30)),
                ('patronymic_teacher', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='django_app.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Listeners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_listener', models.CharField(max_length=30)),
                ('name_listener', models.CharField(max_length=30)),
                ('patronymic_listener', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='django_app.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Group5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_listener', models.CharField(max_length=30)),
                ('name_listener', models.CharField(max_length=30)),
                ('patronymic_listener', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group5', to='django_app.listeners')),
            ],
        ),
        migrations.CreateModel(
            name='Group4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_listener', models.CharField(max_length=30)),
                ('name_listener', models.CharField(max_length=30)),
                ('patronymic_listener', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group4', to='django_app.listeners')),
            ],
        ),
        migrations.CreateModel(
            name='Group3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_listener', models.CharField(max_length=30)),
                ('name_listener', models.CharField(max_length=30)),
                ('patronymic_listener', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group3', to='django_app.listeners')),
            ],
        ),
        migrations.CreateModel(
            name='Group2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_listener', models.CharField(max_length=30)),
                ('name_listener', models.CharField(max_length=30)),
                ('patronymic_listener', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2', to='django_app.listeners')),
            ],
        ),
        migrations.CreateModel(
            name='Group1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_listener', models.CharField(max_length=30)),
                ('name_listener', models.CharField(max_length=30)),
                ('patronymic_listener', models.CharField(max_length=30)),
                ('id_creator', models.IntegerField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group1', to='django_app.listeners')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_listener', models.CharField(max_length=30)),
                ('name_listener', models.CharField(max_length=30)),
                ('patronymic_listener', models.CharField(max_length=30)),
                ('mark', models.IntegerField()),
                ('id_creator', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='django_app.subjects')),
            ],
        ),
    ]
