# Generated by Django 4.2.7 on 2023-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_subjects_teachers_listeners_group5_group4_group3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecords',
            name='listener_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
